# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['model_path', 'learn', 'categories', 'examples', 'intf', 'get_dog_breed', 'classify_images']

# %% app.ipynb 2
from nbdev.showdoc import *
from fastai.vision.all import *
from pathlib import Path
import gradio as gr
import torch

# %% app.ipynb 3
def get_dog_breed(o):
    folder_name = Path(o).parent.name
    breed = str(folder_name).split('-')[-1]
    return ' '.join(breed.split('_'))

# %% app.ipynb 4
model_path = Path(r"dog_breeds_clf_model.pkl")
learn = load_learner(model_path)

# %% app.ipynb 5
categories = learn.dls.vocab

def classify_images(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% app.ipynb 6
examples = ['black_labrador_retriever.jpg', 'great_dane.jpg']

intf = gr.Interface(fn=classify_images, inputs="image", outputs="label", examples=examples)
intf.launch(inline=False)
